### ISSUE TITLE
Pose matrix from Homography is not correct 

### ISSUE THREAD

**Issue by njanirudh** [njanirudh/Augmented-Reality#6]

**Comment by trungbanh** [comment]
i think you should check camera calibration again because this image isn't shot by your cam that you must re compute it

**Comment by trungbanh** [comment]
https://opencv-java-tutorials.readthedocs.io/en/latest/09-camera-calibration.html#what-is-the-camera-calibration

**Comment by njanirudh** [comment]
Thanks
I will check again if I need to recalibrate the camera
