### ISSUE TITLE
import cv2.aruco does not work in cv2 version 3.4.2

### ISSUE THREAD

**Issue by trungbanh** [njanirudh/Augmented-Reality#8]
import cv2.aruco as aruco
ModuleNotFoundError: No module named 'cv2.aruco

**Comment by njanirudh** [comment]
https://stackoverflow.com/questions/45972357/python-opencv-aruco-no-module-named-cv2-aruco

Please uninstall opencv-python and then install opencv-contrib-python

**Comment by trungbanh** [comment]
if i remove opencv-python python can not find cv2

**Comment by njanirudh** [comment]
when you install 'opencv-contrib-python' the opencv-python gets automatically installed. Can you please check it and let me know? 
This is even given in the stackoverflow link above ...the 2nd Answer

**Comment by trungbanh** [comment]
i fix it 
i check version again and update it to latest version is 3.4.5.20
your requirements.txt is still use 3.4.2

**Comment by njanirudh** [comment]
ok..I will make the changes to the requirement.txt
Thanks.

I will close the issue
